### ISSUE TITLE
Communication pattern of rfc discussion

### ISSUE THREAD

**Issue by DSchrupert** [networknt/light-rfcs#1]
Hi @stevehu,

Could you please share the communication pattern you would like to see being used with each rfc? 

Ie. if we would like to discuss light-bot/rfc-0001 within https://github.com/networknt/light-rfcs/blob/master/light-bot/0001-logit-bot-windows-version.md, do we open an issue in this repo with a specific name first with questions and comments? Or are they discussed by commits to the file directly?

**Comment by DSchrupert** [comment]
Oh sorry! Just saw the https://github.com/networknt/light-rfcs#support section in the README.md.. closing.

**Comment by stevehu** [comment]
I think it would be a good idea that we create an issue for each RFC in the corresponding repository.
